import type { Metadata } from "next";
import { site } from "@/content/site";

// Generated by app/opengraph-image.tsx. Listed explicitly because a page-level openGraph block replaces the inherited one.
const OG_IMAGE = { url: "/opengraph-image", width: 1200, height: 630, alt: site.name };

/**
 * Next replaces openGraph/twitter objects wholesale when a page sets them, and
 * inherits the layout's when it does not. Every indexable page builds its own.
 */
export function pageMetadata({ title, description, path }: { title?: string; description: string; path: string }): Metadata {
  const ogTitle = title ? `${title} — ${site.shortName}` : site.name;
  return {
    ...(title ? { title } : {}),
    description,
    alternates: { canonical: path },
    openGraph: { type: "website", siteName: site.name, locale: "en_US", url: path, title: ogTitle, description, images: [OG_IMAGE] },
    twitter: { card: "summary_large_image", title: ogTitle, description, images: [OG_IMAGE.url] },
  };
}
