/**
 * Generated by scripts/build-map.mjs. The dotted world image and the numbers that map
 * a latitude/longitude onto it (ellipsoidal Mercator, as dotted-map projects it).
 */
export const WORLD_MAP = {
  src: "/map/world.69143cd7.svg",
  width: 148,
  height: 72,
  xMin: -18701674.453269962,
  xRange: 38739182.796059206,
  yMax: 12474416.630890086,
  yRange: 18887941.225053728,
} as const;
