// Builds the dotted world map used by components/ui/map.tsx.
//
// dotted-map computes which grid points fall on land, which takes a moment and
// pulls in every country outline, so it runs here once instead of in the page:
// the dots go to a static, cached SVG and the projection numbers go to
// lib/world-map.ts, where the component uses them to place pins exactly.
//
//   node scripts/build-map.mjs
import { createHash } from "node:crypto";
import { readdirSync, rmSync, writeFileSync, mkdirSync } from "node:fs";
import proj4 from "proj4";
import { getMapJSON } from "dotted-map";

// Cropped to where the regions are: no Antarctica, no high Arctic, and wide enough
// on the right that New Zealand is on the map.
const OPTIONS = { height: 72, grid: "diagonal", region: { lat: { min: -50, max: 74 }, lng: { min: -168, max: 180 } } };
const RADIUS = 0.24;

const map = JSON.parse(getMapJSON(OPTIONS));
const round = (n) => Math.round(n * 100) / 100;

const circles = Object.values(map.points)
  .map((p) => `<circle cx="${round(p.x)}" cy="${round(p.y)}" r="${RADIUS}"/>`)
  .join("");
const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${map.width} ${map.height}"><g fill="#fff">${circles}</g></svg>`;

mkdirSync("public/map", { recursive: true });
for (const f of readdirSync("public/map")) if (f.startsWith("world.")) rmSync(`public/map/${f}`);
const hash = createHash("sha256").update(svg).digest("hex").slice(0, 8);
const src = `/map/world.${hash}.svg`;
writeFileSync(`public${src}`, svg);

// The component reimplements the ellipsoidal Mercator in a few lines; check it against proj4.
const A = 6378137;
const E = 0.0818191908426215;
const merc = (lat, lng) => {
  const phi = (lat * Math.PI) / 180;
  const s = Math.sin(phi);
  return [A * ((lng * Math.PI) / 180), A * Math.log(Math.tan(Math.PI / 4 + phi / 2) * ((1 - E * s) / (1 + E * s)) ** (E / 2))];
};
for (const [lat, lng] of [[51.5, -0.13], [-36.85, 174.76], [40.71, -74]]) {
  const [px, py] = proj4("+proj=merc +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m", [lng, lat]);
  const [mx, my] = merc(lat, lng);
  if (Math.abs(px - mx) > 1 || Math.abs(py - my) > 1) throw new Error(`projection mismatch at ${lat},${lng}`);
}

const ts = `/**
 * Generated by scripts/build-map.mjs. The dotted world image and the numbers that map
 * a latitude/longitude onto it (ellipsoidal Mercator, as dotted-map projects it).
 */
export const WORLD_MAP = {
  src: "${src}",
  width: ${map.width},
  height: ${map.height},
  xMin: ${map.X_MIN},
  xRange: ${map.X_RANGE},
  yMax: ${map.Y_MAX},
  yRange: ${map.Y_RANGE},
} as const;
`;
writeFileSync("lib/world-map.ts", ts);
console.log(`${src}: ${Object.keys(map.points).length} dots, ${svg.length} bytes, ${map.width}x${map.height}`);
